### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by FiveEYZ** [DOTNET2016/Happy#1]
- [x] Set clock 
- [x] Start Clock
- [x] Stop Clock
- [x] Get input to minute
- [x] Get input to hour
- [x] Clean the house
- [x] Move logic to clock
- [x] Implement alarms
- [ ] Easter eggs(?)

**Comment by molebox** [comment]
har gjort input to minute och input to hour.
